name: Daily Price Scraper

permissions:
  contents: write

on:
  schedule:
    - cron: '0 10 * * *'  # Horario de ejecución: 10AM UTC = 7AM ARG
  workflow_dispatch:      # Permite ejecución manual

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: python -m playwright install --with-deps

      - name: Run all supermarkets scraper
        run: python scrape_all_async_v2.py

      - name: Normalize product names
        run: python unify_product_names.py

      - name: Commit & push generated CSVs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add Data/Cleaned/*.csv Data/Used/*.csv
          git commit -m "Add generated CSVs for run ${{ github.run_number }}" || echo "No changes to commit"
          git push origin HEAD:main
