name: Daily Price Scraper

on:
  schedule:
    - cron: '0 10 * * *'    # 07:00 ARG = 10:00 UTC
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers (Python)
        run: |
          python -m playwright install --with-deps

      - name: Debug — listar Data antes del scraping
        run: ls -R Data || echo "No existe carpeta Data aún"

      - name: Run all supermarkets scraper
        run: python scrape_all_async_v2.py

      - name: Debug — listar Data/Raw después del scraping
        run: ls -R Data/Raw || echo "Data/Raw sigue vacío"

      - name: Normalize product names
        run: python unify_product_names.py

      - name: Upload raw CSVs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: precios-raw
          path: Data/Raw/*.csv
